import reactPlugin from '@eslint-react/eslint-plugin';
import reactHooksPlugin from 'eslint-plugin-react-hooks';
import tseslint from 'typescript-eslint';

const typeAwareRules = {
  '@typescript-eslint/no-duplicate-type-constituents': 'error',
  '@typescript-eslint/no-redundant-type-constituents': 'error',
  '@typescript-eslint/no-unnecessary-type-assertion': 'error',
  '@typescript-eslint/no-unsafe-argument': 'error',
  '@typescript-eslint/no-unsafe-assignment': 'error',
  '@typescript-eslint/no-unsafe-call': 'error',
  '@typescript-eslint/no-unsafe-enum-comparison': 'error',
  '@typescript-eslint/no-unsafe-member-access': 'error',
  '@typescript-eslint/no-unsafe-return': 'error',
  '@typescript-eslint/no-unsafe-unary-minus': 'error',
  '@typescript-eslint/prefer-promise-reject-errors': 'error',
  '@typescript-eslint/restrict-template-expressions': 'error',
  '@typescript-eslint/triple-slash-reference': 'error',
  '@typescript-eslint/unbound-method': 'error',
};

const reactResidualRules = {
  '@eslint-react/error-boundaries': 'error',
  '@eslint-react/no-access-state-in-setstate': 'error',
  '@eslint-react/no-children-count': 'warn',
  '@eslint-react/no-children-for-each': 'warn',
  '@eslint-react/no-children-map': 'warn',
  '@eslint-react/no-children-only': 'warn',
  '@eslint-react/no-children-to-array': 'warn',
  '@eslint-react/no-clone-element': 'warn',
  '@eslint-react/no-component-will-mount': 'error',
  '@eslint-react/no-component-will-receive-props': 'error',
  '@eslint-react/no-component-will-update': 'error',
  '@eslint-react/no-context-provider': 'warn',
  '@eslint-react/no-create-ref': 'error',
  '@eslint-react/no-direct-mutation-state': 'error',
  '@eslint-react/no-leaked-conditional-rendering': 'error',
  '@eslint-react/no-nested-lazy-component-declarations': 'error',
  '@eslint-react/no-redundant-should-component-update': 'error',
  '@eslint-react/no-set-state-in-component-did-mount': 'warn',
  '@eslint-react/no-set-state-in-component-did-update': 'warn',
  '@eslint-react/no-set-state-in-component-will-update': 'warn',
  '@eslint-react/no-unnecessary-use-prefix': 'warn',
  '@eslint-react/no-unsafe-component-will-mount': 'warn',
  '@eslint-react/no-unsafe-component-will-receive-props': 'warn',
  '@eslint-react/no-unsafe-component-will-update': 'warn',
  '@eslint-react/no-unused-class-component-members': 'warn',
  '@eslint-react/no-use-context': 'warn',
  '@eslint-react/purity': 'warn',
  '@eslint-react/set-state-in-effect': 'warn',
  '@eslint-react/set-state-in-render': 'error',
  '@eslint-react/unsupported-syntax': 'error',
  '@eslint-react/use-memo': 'error',
  '@eslint-react/use-state': 'warn',
  '@eslint-react/jsx-no-key-after-spread': 'error',
  '@eslint-react/dom-no-find-dom-node': 'error',
  '@eslint-react/dom-no-flush-sync': 'error',
  '@eslint-react/dom-no-hydrate': 'error',
  '@eslint-react/dom-no-render': 'error',
  '@eslint-react/dom-no-unsafe-iframe-sandbox': 'warn',
  '@eslint-react/dom-no-use-form-state': 'error',
  '@eslint-react/web-api-no-leaked-event-listener': 'warn',
  '@eslint-react/web-api-no-leaked-interval': 'warn',
  '@eslint-react/web-api-no-leaked-resize-observer': 'warn',
  '@eslint-react/web-api-no-leaked-timeout': 'warn',
  '@eslint-react/naming-convention-context-name': 'warn',
  '@eslint-react/naming-convention-id-name': 'warn',
  '@eslint-react/naming-convention-ref-name': 'warn',
  'react-hooks/config': 'error',
  'react-hooks/error-boundaries': 'error',
  'react-hooks/gating': 'error',
  'react-hooks/globals': 'error',
  'react-hooks/immutability': 'error',
  'react-hooks/purity': 'error',
  'react-hooks/set-state-in-effect': 'warn',
  'react-hooks/set-state-in-render': 'error',
  'react-hooks/static-components': 'error',
  'react-hooks/unsupported-syntax': 'warn',
  'react-hooks/use-memo': 'error',
};

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      'apps/*/dist/**',
      'apps/*/coverage/**',
      '.mango/out/**',
      'apps/frontend/src/routeTree.gen.ts',
    ],
  },
  {
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      ecmaVersion: 'latest',
      parser: tseslint.parser,
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
      sourceType: 'module',
    },
    plugins: {
      '@typescript-eslint': tseslint.plugin,
    },
    rules: typeAwareRules,
  },
  {
    files: ['apps/frontend/**/*.{ts,tsx}'],
    plugins: {
      '@eslint-react': reactPlugin,
      'react-hooks': reactHooksPlugin,
    },
    rules: reactResidualRules,
    settings: reactPlugin.configs['recommended-type-checked'].settings,
  }
);
