/**
 * Generates `spec/fixtures/1/ssh-argv.json`, the corpus both SDKs build the
 * same `ssh` command line from.
 *
 * The argv is produced by the reference builder rather than typed by hand, so
 * an option the preset gains cannot be transcribed into the corpus wrongly.
 * The committed file is the fixture; CI regenerates it and fails when the
 * output differs, so an edit here is a deliberate corpus change — and the Rust
 * suite reading the same file is what proves the two SDKs agree.
 *
 * @example
 * bun ./scripts/fixtures/generate-ssh-argv.ts          # rewrite the file
 * bun ./scripts/fixtures/generate-ssh-argv.ts --check  # exit 1 when stale
 */

import { type SshArgvOptions, sshArgv } from '../../packages/protocol/src/transports/ssh';

const OUTPUT = new URL('../../spec/fixtures/1/ssh-argv.json', import.meta.url);

/** The field a refusal is about; the Rust error carries the same name. */
type Reason = 'host' | 'user' | 'port' | 'connectTimeoutSeconds' | 'command';

interface Accepted {
  readonly name: string;
  readonly options: SshArgvOptions;
}

interface Rejected {
  readonly name: string;
  /** Loosely typed: several cases are values the type system already refuses. */
  readonly options: Record<string, unknown>;
  readonly reason: Reason;
}

const ACCEPTED: readonly Accepted[] = [
  {
    name: 'y_host_and_command',
    options: { host: 'build-box', command: ['mango-runtime'] },
  },
  {
    name: 'y_user_and_quoted_arguments',
    options: {
      host: 'build-box',
      user: 'deploy',
      command: ['/opt/mango/runtime', '--stdio', '--name', "it's mine"],
    },
  },
  {
    name: 'y_identity_file_and_port',
    options: {
      host: 'build-box',
      port: 2222,
      identityFile: '/home/u/.ssh/id_ed25519',
      command: ['mango-runtime', '--stdio'],
    },
  },
  {
    name: 'y_home_relative_remote_path',
    options: { host: 'build-box', command: ['~/bin/mango-runtime', '--stdio'] },
  },
  {
    name: 'y_custom_connect_timeout',
    options: { host: 'build-box', command: ['mango-runtime'], connectTimeoutSeconds: 20 },
  },
];

const REJECTED: readonly Rejected[] = [
  {
    name: 'n_host_could_become_an_option',
    options: { host: '-oProxyCommand=touch /tmp/x', command: ['mango-runtime'] },
    reason: 'host',
  },
  {
    name: 'n_host_with_whitespace',
    options: { host: 'build box', command: ['mango-runtime'] },
    reason: 'host',
  },
  { name: 'n_host_empty', options: { host: '', command: ['mango-runtime'] }, reason: 'host' },
  {
    name: 'n_user_could_become_an_option',
    options: { host: 'build-box', user: '-oX=1', command: ['mango-runtime'] },
    reason: 'user',
  },
  {
    name: 'n_port_zero',
    options: { host: 'build-box', port: 0, command: ['mango-runtime'] },
    reason: 'port',
  },
  {
    name: 'n_port_above_the_range',
    options: { host: 'build-box', port: 65536, command: ['mango-runtime'] },
    reason: 'port',
  },
  { name: 'n_command_empty', options: { host: 'build-box', command: [] }, reason: 'command' },
  {
    name: 'n_command_remote_path_empty',
    options: { host: 'build-box', command: [''] },
    reason: 'command',
  },
  {
    name: 'n_connect_timeout_zero',
    options: { host: 'build-box', command: ['mango-runtime'], connectTimeoutSeconds: 0 },
    reason: 'connectTimeoutSeconds',
  },
];

/** The words the refusal message must contain, so `reason` is not a label nobody checks. */
const MESSAGE_PREFIX: Record<Reason, string> = {
  host: 'ssh host is',
  user: 'ssh user is',
  port: 'ssh port is',
  connectTimeoutSeconds: 'ssh connectTimeoutSeconds is',
  command: 'ssh command is',
};

function accepted(item: Accepted): Record<string, unknown> {
  return {
    name: item.name,
    verdict: 'accept',
    options: item.options,
    argv: sshArgv(item.options),
  };
}

function rejected(item: Rejected): Record<string, unknown> {
  let message: string | undefined;
  try {
    sshArgv(item.options as unknown as SshArgvOptions);
  } catch (cause) {
    message = cause instanceof Error ? cause.message : String(cause);
  }
  if (message === undefined) {
    throw new Error(`${item.name}: expected sshArgv to refuse these options, it returned an argv`);
  }
  const prefix = MESSAGE_PREFIX[item.reason];
  if (!message.startsWith(prefix)) {
    throw new Error(
      `${item.name}: refusal is ${JSON.stringify(message)}; expected one starting ${JSON.stringify(prefix)}`
    );
  }
  return { name: item.name, verdict: 'reject', options: item.options, reason: item.reason };
}

const document = {
  $comment:
    'ssh launcher argv: both SDKs must build the same command line for the same inputs. Generated by scripts/fixtures/generate-ssh-argv.ts; edit the generator, never this file. A reject case names the field the preset refuses; an implementation whose types already refuse the value (a port outside 1-65535, say) satisfies the case by construction.',
  cases: [...ACCEPTED.map(accepted), ...REJECTED.map(rejected)],
};

const text = `${JSON.stringify(document, null, 2)}\n`;
const check = process.argv.includes('--check');
const current = await Bun.file(OUTPUT)
  .text()
  .catch(() => '');

if (check) {
  if (current !== text) {
    console.error(
      'spec/fixtures/1/ssh-argv.json is stale; run bun ./scripts/fixtures/generate-ssh-argv.ts'
    );
    process.exit(1);
  }
  console.warn('ssh-argv.json is up to date');
} else {
  await Bun.write(OUTPUT, text);
  console.warn(`wrote ${document.cases.length} cases to spec/fixtures/1/ssh-argv.json`);
}
