/**
 * Installs MangoStudio-managed Cursor hooks that hard-deny built-in SDK tools.
 */

import { chmod, mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { getCursorAgentDir } from '../../../lib/mango-paths';
import { CURSOR_CUSTOM_USER_TOOLS_SERVER } from './hook-policy';

const DENY_SCRIPT_SOURCE = `#!/usr/bin/env node
/**
 * MangoStudio-managed Cursor hook: deny built-in tools, allow custom-user-tools only.
 * Generated by ensureCursorAgentHooks — keep in sync with hook-policy.ts.
 */
import { readFileSync } from 'node:fs';

const CUSTOM_USER_TOOLS = ${JSON.stringify(CURSOR_CUSTOM_USER_TOOLS_SERVER)};

function isRecord(value) {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function readString(value) {
  return typeof value === 'string' && value.trim() ? value.trim() : undefined;
}

function isCustomUserTools(payload) {
  if (!isRecord(payload)) return false;
  const provider =
    readString(payload.provider_identifier) ??
    readString(payload.providerIdentifier) ??
    readString(payload.mcp_server) ??
    readString(payload.server);
  if (provider === CUSTOM_USER_TOOLS) return true;
  const toolName = readString(payload.tool_name) ?? readString(payload.toolName) ?? '';
  if (toolName.includes(CUSTOM_USER_TOOLS)) return true;
  const name = readString(payload.name) ?? '';
  return name.includes(CUSTOM_USER_TOOLS);
}

function evaluate(payload) {
  if (isCustomUserTools(payload)) return { permission: 'allow' };
  return {
    permission: 'deny',
    user_message: 'Built-in Cursor tools are disabled. Use the MangoStudio tools exposed for this chat.',
    agent_message:
      'Built-in Cursor tools are blocked by MangoStudio policy. Use the custom-user-tools MCP tools instead.',
  };
}

let raw = '';
try {
  raw = readFileSync(0, 'utf8');
} catch {
  process.exit(1);
}

let payload;
try {
  payload = JSON.parse(raw);
} catch {
  process.exit(1);
}

const decision = evaluate(payload);
process.stdout.write(JSON.stringify(decision));
`;

/**
 * Ensures ~/.mango/cursor-agent/.cursor/hooks.json and the deny script exist.
 * Returns the managed Cursor agent working directory (SDK local.cwd).
 */
export async function ensureCursorAgentHooks(nodePath: string): Promise<string> {
  const agentDir = getCursorAgentDir();
  const cursorDir = join(agentDir, '.cursor');
  const hooksDir = join(cursorDir, 'hooks');
  const denyScriptPath = join(hooksDir, 'deny-builtins.mjs');

  await mkdir(hooksDir, { recursive: true });
  await writeFile(denyScriptPath, DENY_SCRIPT_SOURCE, 'utf8');
  await chmod(denyScriptPath, 0o755);

  const hookCommand = buildCursorHookCommand(nodePath, denyScriptPath);
  const hooksConfig = {
    version: 1,
    hooks: {
      preToolUse: [{ command: hookCommand, failClosed: true }],
      beforeShellExecution: [{ command: hookCommand, failClosed: true }],
      beforeReadFile: [{ command: hookCommand, failClosed: true }],
      beforeMCPExecution: [{ command: hookCommand, failClosed: true }],
    },
  };

  await writeFile(
    join(cursorDir, 'hooks.json'),
    `${JSON.stringify(hooksConfig, null, 2)}\n`,
    'utf8'
  );
  return agentDir;
}

export function buildCursorHookCommand(
  nodePath: string,
  denyScriptPath: string,
  platform: NodeJS.Platform = process.platform
): string {
  return `${quoteHookCommandArg(nodePath, platform)} ${quoteHookCommandArg(denyScriptPath, platform)}`;
}

export function quoteHookCommandArg(
  value: string,
  platform: NodeJS.Platform = process.platform
): string {
  if (platform === 'win32') {
    return `"${value.replace(/(\\+)(?=("|$))/g, '$1$1').replace(/"/g, '\\"')}"`;
  }

  return `'${value.replace(/'/g, `'\\''`)}'`;
}
