/** Canonical error code constants shared across API and frontend. */
export const ERROR_CODES = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  METHOD_NOT_ALLOWED: 'METHOD_NOT_ALLOWED',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION: 'VALIDATION',
  CONFLICT: 'CONFLICT',
  PROVIDER_ERROR: 'PROVIDER_ERROR',
  GENERATION_EMPTY: 'GENERATION_EMPTY',
  OWNERSHIP: 'OWNERSHIP',
  RATE_LIMITED: 'RATE_LIMITED',
  UNSUPPORTED: 'UNSUPPORTED',
  CHATGPT_REAUTH_REQUIRED: 'CHATGPT_REAUTH_REQUIRED',
  NOTHING_TO_COMMIT: 'NOTHING_TO_COMMIT',
  AMEND_WITHOUT_HEAD: 'AMEND_WITHOUT_HEAD',
  SIGNING_FAILED: 'SIGNING_FAILED',
  STASH_CONFLICT: 'STASH_CONFLICT',
  CHECKOUT_BLOCKED: 'CHECKOUT_BLOCKED',
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  NON_FAST_FORWARD: 'NON_FAST_FORWARD',
  HISTORY_DIVERGED: 'HISTORY_DIVERGED',
  GIT_LOCKED: 'GIT_LOCKED',
  GIT_COMMAND_FAILED: 'GIT_COMMAND_FAILED',
  INTERNAL: 'INTERNAL',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
