// Event shapes with runtime validation live in `./schemas` (the canonical
// source). They are re-exported here so the discriminated `StreamChunk` union
// and existing `@mangostudio/shared/streaming` imports keep one definition.
export type {
  SSEContextEvent,
  SSEContinuationTransitionEvent,
  SSEDoneEvent,
  SSEErrorEvent,
  SSEFallbackEvent,
  SSEImageGenerationCompletedEvent,
  SSEImageGenerationFailedEvent,
  SSEImageGenerationStartedEvent,
  SSEMcpElicitationRequestEvent,
  SSEMcpMediaEvent,
  SSEQuestionEvent,
  SSESubagentCompletedEvent,
  SSESubagentFailedEvent,
  SSESubagentStartedEvent,
  SSESubagentTextEvent,
  SSESubagentToolCallStartedEvent,
  SSESystemEvent,
  SSETextEvent,
  SSEThinkingEvent,
  SSEThinkingStartEvent,
  SSETodoUpdateEvent,
  SSEToolCallCompletedEvent,
  SSEToolCallStartedEvent,
  SSEToolExecutionEvent,
  SSEToolResultEvent,
  SSEUserMessageIdEvent,
  StreamChunk,
} from './schemas';
