import type { NodeReleaseSchedule } from './lts-policy';

/**
 * Generated by scripts/update-node-release-schedule.ts from nodejs/Release and
 * nodejs.org/dist/index.json. Do not edit by hand.
 */
export const NODE_RELEASE_SCHEDULE = {
  generatedAt: '2026-07-26',
  lines: [
    {
      major: 16,
      start: '2021-04-20',
      lts: '2021-10-26',
      maintenance: '2022-10-18',
      end: '2023-09-11',
      codename: 'gallium',
      latest: '16.20.2',
    },
    {
      major: 17,
      start: '2021-10-19',
      maintenance: '2022-04-01',
      end: '2022-06-01',
      latest: '17.9.1',
    },
    {
      major: 18,
      start: '2022-04-19',
      lts: '2022-10-25',
      maintenance: '2023-10-18',
      end: '2025-04-30',
      codename: 'hydrogen',
      latest: '18.20.8',
    },
    {
      major: 19,
      start: '2022-10-18',
      maintenance: '2023-04-01',
      end: '2023-06-01',
      latest: '19.9.0',
    },
    {
      major: 20,
      start: '2023-04-18',
      lts: '2023-10-24',
      maintenance: '2024-10-22',
      end: '2026-04-30',
      codename: 'iron',
      latest: '20.20.2',
    },
    {
      major: 21,
      start: '2023-10-17',
      maintenance: '2024-04-01',
      end: '2024-06-01',
      latest: '21.7.3',
    },
    {
      major: 22,
      start: '2024-04-24',
      lts: '2024-10-29',
      maintenance: '2025-10-21',
      end: '2027-04-30',
      codename: 'jod',
      latest: '22.23.1',
    },
    {
      major: 23,
      start: '2024-10-16',
      maintenance: '2025-04-01',
      end: '2025-06-01',
      latest: '23.11.1',
    },
    {
      major: 24,
      start: '2025-05-06',
      lts: '2025-10-28',
      maintenance: '2026-10-20',
      end: '2028-04-30',
      codename: 'krypton',
      latest: '24.18.0',
    },
    {
      major: 25,
      start: '2025-10-15',
      maintenance: '2026-04-01',
      end: '2026-06-01',
      latest: '25.9.0',
    },
    {
      major: 26,
      start: '2026-05-05',
      lts: '2026-10-28',
      maintenance: '2027-10-20',
      end: '2029-04-30',
      latest: '26.5.0',
    },
    {
      major: 27,
      start: '2027-04-22',
      maintenance: '2027-10-20',
      end: '2030-04-30',
    },
  ],
} as const satisfies NodeReleaseSchedule;
