/**
 * Generates the throwaway modules that embed the built frontend into a
 * standalone binary. Both modules are emitted under `.mango/out/embed/`
 * (gitignored, never committed): a manifest that imports every file in
 * `apps/frontend/dist` with Bun's file loader — `bun build --compile` then
 * embeds the bytes and resolves each import to an embedded path servable via
 * `Bun.file()` — and an entry that registers the manifest before booting the
 * real CLI.
 */

import { mkdirSync, readdirSync, writeFileSync } from 'node:fs';
import { join, sep } from 'node:path';

export interface EmbedModuleOptions {
  /** Built frontend directory (apps/frontend/dist). */
  distDir: string;
  /** Output directory for the generated modules (.mango/out/embed). */
  embedDir: string;
  /** Absolute path to apps/api/src/server/embedded-frontend.ts. */
  registryModulePath: string;
  /** Absolute path to the real CLI entrypoint (apps/api/src/index.ts). */
  apiEntryPath: string;
}

export interface EmbedModules {
  entryPath: string;
  manifestPath: string;
  fileCount: number;
}

/**
 * Lists every file under the dist directory as URL paths ('/index.html',
 * '/assets/index-abc.js'). Keys always use '/' separators regardless of the
 * host platform; sorted for deterministic module output.
 */
export function listDistFiles(distDir: string): string[] {
  return readdirSync(distDir, { recursive: true, withFileTypes: true })
    .filter((entry) => entry.isFile())
    .map((entry) => {
      const absolute = join(entry.parentPath, entry.name);
      const relative = absolute.slice(distDir.length).split(sep).filter(Boolean);
      return `/${relative.join('/')}`;
    })
    .sort();
}

/** Renders the manifest module: one file-loader import per dist file, keyed by URL path. */
export function renderFrontendManifestModule(distDir: string, urlPaths: readonly string[]): string {
  const imports = urlPaths.map((urlPath, index) => {
    const filePath = join(distDir, ...urlPath.split('/').filter(Boolean));
    return `import f${index} from ${JSON.stringify(filePath)} with { type: 'file' };`;
  });
  const entries = urlPaths.map((urlPath, index) => `  ${JSON.stringify(urlPath)}: f${index},`);

  return [
    '// Generated by scripts/lib/embed-frontend.ts — do not edit or commit.',
    ...imports,
    '',
    'export const embeddedFrontend: Record<string, string> = {',
    ...entries,
    '};',
    '',
  ].join('\n');
}

/** Renders the compile entrypoint: register the embedded manifest, then boot the CLI. */
export function renderEmbedEntryModule(registryModulePath: string, apiEntryPath: string): string {
  return [
    '// Generated by scripts/lib/embed-frontend.ts — do not edit or commit.',
    `import { registerEmbeddedFrontend } from ${JSON.stringify(registryModulePath)};`,
    "import { embeddedFrontend } from './frontend-manifest';",
    '',
    'registerEmbeddedFrontend(embeddedFrontend);',
    '',
    '// Dynamic import so registration happens before any server module runs.',
    `await import(${JSON.stringify(apiEntryPath)});`,
    '',
  ].join('\n');
}

/** Writes manifest + entry modules and returns the entry to compile. // Usage: writeEmbedModules(options) */
export function writeEmbedModules(options: EmbedModuleOptions): EmbedModules {
  const urlPaths = listDistFiles(options.distDir);
  mkdirSync(options.embedDir, { recursive: true });

  const manifestPath = join(options.embedDir, 'frontend-manifest.ts');
  writeFileSync(manifestPath, renderFrontendManifestModule(options.distDir, urlPaths));

  const entryPath = join(options.embedDir, 'entry.ts');
  writeFileSync(
    entryPath,
    renderEmbedEntryModule(options.registryModulePath, options.apiEntryPath)
  );

  return { entryPath, manifestPath, fileCount: urlPaths.length };
}
