/**
 * Generates the throwaway modules that embed the built frontend into a
 * standalone binary. Both modules are emitted under `.mango/out/embed/`
 * (gitignored, never committed): a manifest that imports every file in
 * `apps/frontend/dist` with Bun's file loader — `bun build --compile` then
 * embeds the bytes and resolves each import to an embedded path servable via
 * `Bun.file()` — and an entry that registers the manifest before booting the
 * real CLI.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { distFilePath, listDistFiles } from '@mangostudio/shared/utils/dist-files';

export interface EmbedModuleOptions {
  /** Built frontend directory (apps/frontend/dist). */
  distDir: string;
  /** Output directory for the generated modules (.mango/out/embed). */
  embedDir: string;
  /** Absolute path to apps/api/src/server/embedded-frontend.ts. */
  registryModulePath: string;
  /** Absolute path to the real CLI entrypoint (apps/api/src/index.ts). */
  apiEntryPath: string;
}

export interface EmbedModules {
  entryPath: string;
  manifestPath: string;
  fileCount: number;
}

/** Renders the manifest module: one file-loader import per dist file, keyed by URL path. */
export function renderFrontendManifestModule(distDir: string, urlPaths: readonly string[]): string {
  const imports = urlPaths.map((urlPath, index) => {
    const filePath = distFilePath(distDir, urlPath);
    return `import f${index} from ${JSON.stringify(filePath)} with { type: 'file' };`;
  });
  const entries = urlPaths.map((urlPath, index) => `  ${JSON.stringify(urlPath)}: f${index},`);

  return [
    '// Generated by scripts/lib/embed-frontend.ts — do not edit or commit.',
    ...imports,
    '',
    'export const embeddedFrontend: Record<string, string> = {',
    ...entries,
    '};',
    '',
  ].join('\n');
}

/** Renders the compile entrypoint: register the embedded manifest, then boot the CLI. */
export function renderEmbedEntryModule(registryModulePath: string, apiEntryPath: string): string {
  return [
    '// Generated by scripts/lib/embed-frontend.ts — do not edit or commit.',
    `import { registerEmbeddedFrontend } from ${JSON.stringify(registryModulePath)};`,
    "import { embeddedFrontend } from './frontend-manifest';",
    '',
    'registerEmbeddedFrontend(embeddedFrontend);',
    '',
    '// Dynamic import so registration happens before any server module runs.',
    `await import(${JSON.stringify(apiEntryPath)});`,
    '',
  ].join('\n');
}

/**
 * Refuse to compile a binary that would ship without its frontend.
 *
 * The embedded manifest is the only place a binary's assets come from — there
 * is no disk fallback to catch a miss. Without this the failure is silent and
 * late: an empty manifest compiles, the binary boots, `registerEmbeddedSpa`
 * finds no `/index.html`, and every route answers API-only. That looks like a
 * server problem to whoever hits it, an hour and a release pipeline away from
 * the build that caused it.
 *
 * `/index.html` specifically, not just a non-empty walk: it is the one file the
 * shell and every SPA deep link resolve to, and a dist that somehow has assets
 * without it is no more servable than an empty one.
 */
function assertEmbeddable(distDir: string, urlPaths: readonly string[]): void {
  if (urlPaths.includes('/index.html')) return;
  throw new Error(
    `Cannot embed a frontend from ${distDir}: no /index.html among ${urlPaths.length} file(s). ` +
      'Build the frontend before compiling the binary.'
  );
}

/** Writes manifest + entry modules and returns the entry to compile. // Usage: writeEmbedModules(options) */
export function writeEmbedModules(options: EmbedModuleOptions): EmbedModules {
  const urlPaths = listDistFiles(options.distDir);
  assertEmbeddable(options.distDir, urlPaths);
  mkdirSync(options.embedDir, { recursive: true });

  const manifestPath = join(options.embedDir, 'frontend-manifest.ts');
  writeFileSync(manifestPath, renderFrontendManifestModule(options.distDir, urlPaths));

  const entryPath = join(options.embedDir, 'entry.ts');
  writeFileSync(
    entryPath,
    renderEmbedEntryModule(options.registryModulePath, options.apiEntryPath)
  );

  return { entryPath, manifestPath, fileCount: urlPaths.length };
}
