//! The bundled Node release schedule, mirroring
//! `apps/shared/src/environments/detection/node-release-schedule.ts`
//! exactly — same majors, same dates, same `latest` patches. That file is
//! generated by `scripts/update-node-release-schedule.ts` from
//! nodejs/Release and nodejs.org/dist/index.json; this port copies its
//! values verbatim rather than regenerating or approximating them, and
//! should be regenerated the same way the TypeScript table is when it next
//! changes.

use super::lts_policy::{NodeReleaseLine, NodeReleaseSchedule};

/// The bundled Node release schedule. See the module docs: this is a
/// value-for-value copy of the TypeScript original, not a re-derivation.
pub const NODE_RELEASE_SCHEDULE: NodeReleaseSchedule = NodeReleaseSchedule {
    generated_at: "2026-07-26",
    lines: &[
        NodeReleaseLine {
            major: 16,
            start: "2021-04-20",
            lts: Some("2021-10-26"),
            maintenance: Some("2022-10-18"),
            end: "2023-09-11",
            codename: Some("gallium"),
            latest: Some("16.20.2"),
        },
        NodeReleaseLine {
            major: 17,
            start: "2021-10-19",
            lts: None,
            maintenance: Some("2022-04-01"),
            end: "2022-06-01",
            codename: None,
            latest: Some("17.9.1"),
        },
        NodeReleaseLine {
            major: 18,
            start: "2022-04-19",
            lts: Some("2022-10-25"),
            maintenance: Some("2023-10-18"),
            end: "2025-04-30",
            codename: Some("hydrogen"),
            latest: Some("18.20.8"),
        },
        NodeReleaseLine {
            major: 19,
            start: "2022-10-18",
            lts: None,
            maintenance: Some("2023-04-01"),
            end: "2023-06-01",
            codename: None,
            latest: Some("19.9.0"),
        },
        NodeReleaseLine {
            major: 20,
            start: "2023-04-18",
            lts: Some("2023-10-24"),
            maintenance: Some("2024-10-22"),
            end: "2026-04-30",
            codename: Some("iron"),
            latest: Some("20.20.2"),
        },
        NodeReleaseLine {
            major: 21,
            start: "2023-10-17",
            lts: None,
            maintenance: Some("2024-04-01"),
            end: "2024-06-01",
            codename: None,
            latest: Some("21.7.3"),
        },
        NodeReleaseLine {
            major: 22,
            start: "2024-04-24",
            lts: Some("2024-10-29"),
            maintenance: Some("2025-10-21"),
            end: "2027-04-30",
            codename: Some("jod"),
            latest: Some("22.23.1"),
        },
        NodeReleaseLine {
            major: 23,
            start: "2024-10-16",
            lts: None,
            maintenance: Some("2025-04-01"),
            end: "2025-06-01",
            codename: None,
            latest: Some("23.11.1"),
        },
        NodeReleaseLine {
            major: 24,
            start: "2025-05-06",
            lts: Some("2025-10-28"),
            maintenance: Some("2026-10-20"),
            end: "2028-04-30",
            codename: Some("krypton"),
            latest: Some("24.18.0"),
        },
        NodeReleaseLine {
            major: 25,
            start: "2025-10-15",
            lts: None,
            maintenance: Some("2026-04-01"),
            end: "2026-06-01",
            codename: None,
            latest: Some("25.9.0"),
        },
        NodeReleaseLine {
            major: 26,
            start: "2026-05-05",
            lts: Some("2026-10-28"),
            maintenance: Some("2027-10-20"),
            end: "2029-04-30",
            codename: None,
            latest: Some("26.5.0"),
        },
        NodeReleaseLine {
            major: 27,
            start: "2027-04-22",
            lts: None,
            maintenance: Some("2027-10-20"),
            end: "2030-04-30",
            codename: None,
            latest: None,
        },
    ],
};

#[cfg(test)]
mod tests {
    use super::NODE_RELEASE_SCHEDULE;

    #[test]
    fn every_bundled_line_is_present_in_order() {
        let majors: Vec<u32> = NODE_RELEASE_SCHEDULE
            .lines
            .iter()
            .map(|line| line.major)
            .collect();
        assert_eq!(majors, vec![16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27]);
    }

    #[test]
    fn the_newest_line_carries_no_latest_patch_yet() {
        let newest = NODE_RELEASE_SCHEDULE
            .lines
            .last()
            .expect("at least one line");
        assert_eq!(newest.major, 27);
        assert!(newest.latest.is_none());
    }
}
