/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedGalleryRouteImport } from './routes/_authenticated/gallery'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSettingsToolsRouteImport } from './routes/_authenticated/settings/tools'
import { Route as AuthenticatedSettingsProvidersRouteImport } from './routes/_authenticated/settings/providers'
import { Route as AuthenticatedSettingsPromptsRouteImport } from './routes/_authenticated/settings/prompts'
import { Route as AuthenticatedSettingsGeneralRouteImport } from './routes/_authenticated/settings/general'
import { Route as AuthenticatedSettingsContextRouteImport } from './routes/_authenticated/settings/context'
import { Route as AuthenticatedSettingsConnectorsRouteImport } from './routes/_authenticated/settings/connectors'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsProvidersIndexRouteImport } from './routes/_authenticated/settings/providers/index'
import { Route as AuthenticatedSettingsProvidersProviderRouteImport } from './routes/_authenticated/settings/providers.$provider'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGalleryRoute = AuthenticatedGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsToolsRoute =
  AuthenticatedSettingsToolsRouteImport.update({
    id: '/tools',
    path: '/tools',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsProvidersRoute =
  AuthenticatedSettingsProvidersRouteImport.update({
    id: '/providers',
    path: '/providers',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsPromptsRoute =
  AuthenticatedSettingsPromptsRouteImport.update({
    id: '/prompts',
    path: '/prompts',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsGeneralRoute =
  AuthenticatedSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsContextRoute =
  AuthenticatedSettingsContextRouteImport.update({
    id: '/context',
    path: '/context',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsConnectorsRoute =
  AuthenticatedSettingsConnectorsRouteImport.update({
    id: '/connectors',
    path: '/connectors',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsProvidersIndexRoute =
  AuthenticatedSettingsProvidersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsProvidersRoute,
  } as any)
const AuthenticatedSettingsProvidersProviderRoute =
  AuthenticatedSettingsProvidersProviderRouteImport.update({
    id: '/$provider',
    path: '/$provider',
    getParentRoute: () => AuthenticatedSettingsProvidersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/gallery': typeof AuthenticatedGalleryRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/connectors': typeof AuthenticatedSettingsConnectorsRoute
  '/settings/context': typeof AuthenticatedSettingsContextRoute
  '/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/settings/prompts': typeof AuthenticatedSettingsPromptsRoute
  '/settings/providers': typeof AuthenticatedSettingsProvidersRouteWithChildren
  '/settings/tools': typeof AuthenticatedSettingsToolsRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/settings/providers/$provider': typeof AuthenticatedSettingsProvidersProviderRoute
  '/settings/providers/': typeof AuthenticatedSettingsProvidersIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/gallery': typeof AuthenticatedGalleryRoute
  '/': typeof AuthenticatedIndexRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/connectors': typeof AuthenticatedSettingsConnectorsRoute
  '/settings/context': typeof AuthenticatedSettingsContextRoute
  '/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/settings/prompts': typeof AuthenticatedSettingsPromptsRoute
  '/settings/tools': typeof AuthenticatedSettingsToolsRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/settings/providers/$provider': typeof AuthenticatedSettingsProvidersProviderRoute
  '/settings/providers': typeof AuthenticatedSettingsProvidersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/gallery': typeof AuthenticatedGalleryRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/connectors': typeof AuthenticatedSettingsConnectorsRoute
  '/_authenticated/settings/context': typeof AuthenticatedSettingsContextRoute
  '/_authenticated/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/_authenticated/settings/prompts': typeof AuthenticatedSettingsPromptsRoute
  '/_authenticated/settings/providers': typeof AuthenticatedSettingsProvidersRouteWithChildren
  '/_authenticated/settings/tools': typeof AuthenticatedSettingsToolsRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/settings/providers/$provider': typeof AuthenticatedSettingsProvidersProviderRoute
  '/_authenticated/settings/providers/': typeof AuthenticatedSettingsProvidersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/gallery'
    | '/settings'
    | '/settings/appearance'
    | '/settings/connectors'
    | '/settings/context'
    | '/settings/general'
    | '/settings/prompts'
    | '/settings/providers'
    | '/settings/tools'
    | '/settings/'
    | '/settings/providers/$provider'
    | '/settings/providers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/gallery'
    | '/'
    | '/settings/appearance'
    | '/settings/connectors'
    | '/settings/context'
    | '/settings/general'
    | '/settings/prompts'
    | '/settings/tools'
    | '/settings'
    | '/settings/providers/$provider'
    | '/settings/providers'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/gallery'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/connectors'
    | '/_authenticated/settings/context'
    | '/_authenticated/settings/general'
    | '/_authenticated/settings/prompts'
    | '/_authenticated/settings/providers'
    | '/_authenticated/settings/tools'
    | '/_authenticated/settings/'
    | '/_authenticated/settings/providers/$provider'
    | '/_authenticated/settings/providers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gallery': {
      id: '/_authenticated/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof AuthenticatedGalleryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/tools': {
      id: '/_authenticated/settings/tools'
      path: '/tools'
      fullPath: '/settings/tools'
      preLoaderRoute: typeof AuthenticatedSettingsToolsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/providers': {
      id: '/_authenticated/settings/providers'
      path: '/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof AuthenticatedSettingsProvidersRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/prompts': {
      id: '/_authenticated/settings/prompts'
      path: '/prompts'
      fullPath: '/settings/prompts'
      preLoaderRoute: typeof AuthenticatedSettingsPromptsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/general': {
      id: '/_authenticated/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof AuthenticatedSettingsGeneralRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/context': {
      id: '/_authenticated/settings/context'
      path: '/context'
      fullPath: '/settings/context'
      preLoaderRoute: typeof AuthenticatedSettingsContextRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/connectors': {
      id: '/_authenticated/settings/connectors'
      path: '/connectors'
      fullPath: '/settings/connectors'
      preLoaderRoute: typeof AuthenticatedSettingsConnectorsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/providers/': {
      id: '/_authenticated/settings/providers/'
      path: '/'
      fullPath: '/settings/providers/'
      preLoaderRoute: typeof AuthenticatedSettingsProvidersIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsProvidersRoute
    }
    '/_authenticated/settings/providers/$provider': {
      id: '/_authenticated/settings/providers/$provider'
      path: '/$provider'
      fullPath: '/settings/providers/$provider'
      preLoaderRoute: typeof AuthenticatedSettingsProvidersProviderRouteImport
      parentRoute: typeof AuthenticatedSettingsProvidersRoute
    }
  }
}

interface AuthenticatedSettingsProvidersRouteChildren {
  AuthenticatedSettingsProvidersProviderRoute: typeof AuthenticatedSettingsProvidersProviderRoute
  AuthenticatedSettingsProvidersIndexRoute: typeof AuthenticatedSettingsProvidersIndexRoute
}

const AuthenticatedSettingsProvidersRouteChildren: AuthenticatedSettingsProvidersRouteChildren =
  {
    AuthenticatedSettingsProvidersProviderRoute:
      AuthenticatedSettingsProvidersProviderRoute,
    AuthenticatedSettingsProvidersIndexRoute:
      AuthenticatedSettingsProvidersIndexRoute,
  }

const AuthenticatedSettingsProvidersRouteWithChildren =
  AuthenticatedSettingsProvidersRoute._addFileChildren(
    AuthenticatedSettingsProvidersRouteChildren,
  )

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsConnectorsRoute: typeof AuthenticatedSettingsConnectorsRoute
  AuthenticatedSettingsContextRoute: typeof AuthenticatedSettingsContextRoute
  AuthenticatedSettingsGeneralRoute: typeof AuthenticatedSettingsGeneralRoute
  AuthenticatedSettingsPromptsRoute: typeof AuthenticatedSettingsPromptsRoute
  AuthenticatedSettingsProvidersRoute: typeof AuthenticatedSettingsProvidersRouteWithChildren
  AuthenticatedSettingsToolsRoute: typeof AuthenticatedSettingsToolsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
  AuthenticatedSettingsConnectorsRoute: AuthenticatedSettingsConnectorsRoute,
  AuthenticatedSettingsContextRoute: AuthenticatedSettingsContextRoute,
  AuthenticatedSettingsGeneralRoute: AuthenticatedSettingsGeneralRoute,
  AuthenticatedSettingsPromptsRoute: AuthenticatedSettingsPromptsRoute,
  AuthenticatedSettingsProvidersRoute:
    AuthenticatedSettingsProvidersRouteWithChildren,
  AuthenticatedSettingsToolsRoute: AuthenticatedSettingsToolsRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedGalleryRoute: typeof AuthenticatedGalleryRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedGalleryRoute: AuthenticatedGalleryRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
