/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedStudioRouteImport } from './routes/_authenticated/studio'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedGalleryRouteImport } from './routes/_authenticated/gallery'
import { Route as AuthenticatedEnvironmentsRouteImport } from './routes/_authenticated/environments'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedLibraryIndexRouteImport } from './routes/_authenticated/library/index'
import { Route as AuthenticatedEnvironmentsIndexRouteImport } from './routes/_authenticated/environments/index'
import { Route as AuthenticatedSettingsToolsRouteImport } from './routes/_authenticated/settings/tools'
import { Route as AuthenticatedSettingsSkillsRouteImport } from './routes/_authenticated/settings/skills'
import { Route as AuthenticatedSettingsProvidersRouteImport } from './routes/_authenticated/settings/providers'
import { Route as AuthenticatedSettingsPromptsRouteImport } from './routes/_authenticated/settings/prompts'
import { Route as AuthenticatedSettingsMetricsRouteImport } from './routes/_authenticated/settings/metrics'
import { Route as AuthenticatedSettingsMcpRouteImport } from './routes/_authenticated/settings/mcp'
import { Route as AuthenticatedSettingsLogsRouteImport } from './routes/_authenticated/settings/logs'
import { Route as AuthenticatedSettingsGitRouteImport } from './routes/_authenticated/settings/git'
import { Route as AuthenticatedSettingsGeneralRouteImport } from './routes/_authenticated/settings/general'
import { Route as AuthenticatedSettingsExternalApiRouteImport } from './routes/_authenticated/settings/external-api'
import { Route as AuthenticatedSettingsContextRouteImport } from './routes/_authenticated/settings/context'
import { Route as AuthenticatedSettingsConnectorsRouteImport } from './routes/_authenticated/settings/connectors'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAgentsRouteImport } from './routes/_authenticated/settings/agents'
import { Route as AuthenticatedLibrarySubagentsRouteImport } from './routes/_authenticated/library/subagents'
import { Route as AuthenticatedLibrarySkillsRouteImport } from './routes/_authenticated/library/skills'
import { Route as AuthenticatedLibrarySettingsRouteImport } from './routes/_authenticated/library/settings'
import { Route as AuthenticatedLibraryInstructionsRouteImport } from './routes/_authenticated/library/instructions'
import { Route as AuthenticatedLibraryBackupsRouteImport } from './routes/_authenticated/library/backups'
import { Route as AuthenticatedLibraryResourceKeyRouteImport } from './routes/_authenticated/library/$resourceKey'
import { Route as AuthenticatedEnvironmentsRuntimesRouteImport } from './routes/_authenticated/environments/runtimes'
import { Route as AuthenticatedEnvironmentsLibraryRouteImport } from './routes/_authenticated/environments/library'
import { Route as AuthenticatedEnvironmentsHealthRouteImport } from './routes/_authenticated/environments/health'
import { Route as AuthenticatedEnvironmentsAgentsRouteImport } from './routes/_authenticated/environments/agents'
import { Route as AuthenticatedSettingsProvidersIndexRouteImport } from './routes/_authenticated/settings/providers/index'
import { Route as AuthenticatedEnvironmentsLibraryIndexRouteImport } from './routes/_authenticated/environments/library/index'
import { Route as AuthenticatedSettingsProvidersProviderRouteImport } from './routes/_authenticated/settings/providers.$provider'
import { Route as AuthenticatedEnvironmentsLibrarySubagentsRouteImport } from './routes/_authenticated/environments/library/subagents'
import { Route as AuthenticatedEnvironmentsLibrarySkillsRouteImport } from './routes/_authenticated/environments/library/skills'
import { Route as AuthenticatedEnvironmentsLibrarySettingsRouteImport } from './routes/_authenticated/environments/library/settings'
import { Route as AuthenticatedEnvironmentsLibraryInstructionsRouteImport } from './routes/_authenticated/environments/library/instructions'
import { Route as AuthenticatedEnvironmentsLibraryBackupsRouteImport } from './routes/_authenticated/environments/library/backups'
import { Route as AuthenticatedEnvironmentsLibraryResourceKeyRouteImport } from './routes/_authenticated/environments/library/$resourceKey'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudioRoute = AuthenticatedStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGalleryRoute = AuthenticatedGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEnvironmentsRoute =
  AuthenticatedEnvironmentsRouteImport.update({
    id: '/environments',
    path: '/environments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedLibraryIndexRoute =
  AuthenticatedLibraryIndexRouteImport.update({
    id: '/library/',
    path: '/library/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEnvironmentsIndexRoute =
  AuthenticatedEnvironmentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEnvironmentsRoute,
  } as any)
const AuthenticatedSettingsToolsRoute =
  AuthenticatedSettingsToolsRouteImport.update({
    id: '/tools',
    path: '/tools',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsSkillsRoute =
  AuthenticatedSettingsSkillsRouteImport.update({
    id: '/skills',
    path: '/skills',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsProvidersRoute =
  AuthenticatedSettingsProvidersRouteImport.update({
    id: '/providers',
    path: '/providers',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsPromptsRoute =
  AuthenticatedSettingsPromptsRouteImport.update({
    id: '/prompts',
    path: '/prompts',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsMetricsRoute =
  AuthenticatedSettingsMetricsRouteImport.update({
    id: '/metrics',
    path: '/metrics',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsMcpRoute =
  AuthenticatedSettingsMcpRouteImport.update({
    id: '/mcp',
    path: '/mcp',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsLogsRoute =
  AuthenticatedSettingsLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsGitRoute =
  AuthenticatedSettingsGitRouteImport.update({
    id: '/git',
    path: '/git',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsGeneralRoute =
  AuthenticatedSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsExternalApiRoute =
  AuthenticatedSettingsExternalApiRouteImport.update({
    id: '/external-api',
    path: '/external-api',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsContextRoute =
  AuthenticatedSettingsContextRouteImport.update({
    id: '/context',
    path: '/context',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsConnectorsRoute =
  AuthenticatedSettingsConnectorsRouteImport.update({
    id: '/connectors',
    path: '/connectors',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsAgentsRoute =
  AuthenticatedSettingsAgentsRouteImport.update({
    id: '/agents',
    path: '/agents',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedLibrarySubagentsRoute =
  AuthenticatedLibrarySubagentsRouteImport.update({
    id: '/library/subagents',
    path: '/library/subagents',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLibrarySkillsRoute =
  AuthenticatedLibrarySkillsRouteImport.update({
    id: '/library/skills',
    path: '/library/skills',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLibrarySettingsRoute =
  AuthenticatedLibrarySettingsRouteImport.update({
    id: '/library/settings',
    path: '/library/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLibraryInstructionsRoute =
  AuthenticatedLibraryInstructionsRouteImport.update({
    id: '/library/instructions',
    path: '/library/instructions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLibraryBackupsRoute =
  AuthenticatedLibraryBackupsRouteImport.update({
    id: '/library/backups',
    path: '/library/backups',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLibraryResourceKeyRoute =
  AuthenticatedLibraryResourceKeyRouteImport.update({
    id: '/library/$resourceKey',
    path: '/library/$resourceKey',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEnvironmentsRuntimesRoute =
  AuthenticatedEnvironmentsRuntimesRouteImport.update({
    id: '/runtimes',
    path: '/runtimes',
    getParentRoute: () => AuthenticatedEnvironmentsRoute,
  } as any)
const AuthenticatedEnvironmentsLibraryRoute =
  AuthenticatedEnvironmentsLibraryRouteImport.update({
    id: '/library',
    path: '/library',
    getParentRoute: () => AuthenticatedEnvironmentsRoute,
  } as any)
const AuthenticatedEnvironmentsHealthRoute =
  AuthenticatedEnvironmentsHealthRouteImport.update({
    id: '/health',
    path: '/health',
    getParentRoute: () => AuthenticatedEnvironmentsRoute,
  } as any)
const AuthenticatedEnvironmentsAgentsRoute =
  AuthenticatedEnvironmentsAgentsRouteImport.update({
    id: '/agents',
    path: '/agents',
    getParentRoute: () => AuthenticatedEnvironmentsRoute,
  } as any)
const AuthenticatedSettingsProvidersIndexRoute =
  AuthenticatedSettingsProvidersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsProvidersRoute,
  } as any)
const AuthenticatedEnvironmentsLibraryIndexRoute =
  AuthenticatedEnvironmentsLibraryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEnvironmentsLibraryRoute,
  } as any)
const AuthenticatedSettingsProvidersProviderRoute =
  AuthenticatedSettingsProvidersProviderRouteImport.update({
    id: '/$provider',
    path: '/$provider',
    getParentRoute: () => AuthenticatedSettingsProvidersRoute,
  } as any)
const AuthenticatedEnvironmentsLibrarySubagentsRoute =
  AuthenticatedEnvironmentsLibrarySubagentsRouteImport.update({
    id: '/subagents',
    path: '/subagents',
    getParentRoute: () => AuthenticatedEnvironmentsLibraryRoute,
  } as any)
const AuthenticatedEnvironmentsLibrarySkillsRoute =
  AuthenticatedEnvironmentsLibrarySkillsRouteImport.update({
    id: '/skills',
    path: '/skills',
    getParentRoute: () => AuthenticatedEnvironmentsLibraryRoute,
  } as any)
const AuthenticatedEnvironmentsLibrarySettingsRoute =
  AuthenticatedEnvironmentsLibrarySettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedEnvironmentsLibraryRoute,
  } as any)
const AuthenticatedEnvironmentsLibraryInstructionsRoute =
  AuthenticatedEnvironmentsLibraryInstructionsRouteImport.update({
    id: '/instructions',
    path: '/instructions',
    getParentRoute: () => AuthenticatedEnvironmentsLibraryRoute,
  } as any)
const AuthenticatedEnvironmentsLibraryBackupsRoute =
  AuthenticatedEnvironmentsLibraryBackupsRouteImport.update({
    id: '/backups',
    path: '/backups',
    getParentRoute: () => AuthenticatedEnvironmentsLibraryRoute,
  } as any)
const AuthenticatedEnvironmentsLibraryResourceKeyRoute =
  AuthenticatedEnvironmentsLibraryResourceKeyRouteImport.update({
    id: '/$resourceKey',
    path: '/$resourceKey',
    getParentRoute: () => AuthenticatedEnvironmentsLibraryRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/environments': typeof AuthenticatedEnvironmentsRouteWithChildren
  '/gallery': typeof AuthenticatedGalleryRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/studio': typeof AuthenticatedStudioRoute
  '/environments/agents': typeof AuthenticatedEnvironmentsAgentsRoute
  '/environments/health': typeof AuthenticatedEnvironmentsHealthRoute
  '/environments/library': typeof AuthenticatedEnvironmentsLibraryRouteWithChildren
  '/environments/runtimes': typeof AuthenticatedEnvironmentsRuntimesRoute
  '/library/$resourceKey': typeof AuthenticatedLibraryResourceKeyRoute
  '/library/backups': typeof AuthenticatedLibraryBackupsRoute
  '/library/instructions': typeof AuthenticatedLibraryInstructionsRoute
  '/library/settings': typeof AuthenticatedLibrarySettingsRoute
  '/library/skills': typeof AuthenticatedLibrarySkillsRoute
  '/library/subagents': typeof AuthenticatedLibrarySubagentsRoute
  '/settings/agents': typeof AuthenticatedSettingsAgentsRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/connectors': typeof AuthenticatedSettingsConnectorsRoute
  '/settings/context': typeof AuthenticatedSettingsContextRoute
  '/settings/external-api': typeof AuthenticatedSettingsExternalApiRoute
  '/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/settings/git': typeof AuthenticatedSettingsGitRoute
  '/settings/logs': typeof AuthenticatedSettingsLogsRoute
  '/settings/mcp': typeof AuthenticatedSettingsMcpRoute
  '/settings/metrics': typeof AuthenticatedSettingsMetricsRoute
  '/settings/prompts': typeof AuthenticatedSettingsPromptsRoute
  '/settings/providers': typeof AuthenticatedSettingsProvidersRouteWithChildren
  '/settings/skills': typeof AuthenticatedSettingsSkillsRoute
  '/settings/tools': typeof AuthenticatedSettingsToolsRoute
  '/environments/': typeof AuthenticatedEnvironmentsIndexRoute
  '/library/': typeof AuthenticatedLibraryIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/environments/library/$resourceKey': typeof AuthenticatedEnvironmentsLibraryResourceKeyRoute
  '/environments/library/backups': typeof AuthenticatedEnvironmentsLibraryBackupsRoute
  '/environments/library/instructions': typeof AuthenticatedEnvironmentsLibraryInstructionsRoute
  '/environments/library/settings': typeof AuthenticatedEnvironmentsLibrarySettingsRoute
  '/environments/library/skills': typeof AuthenticatedEnvironmentsLibrarySkillsRoute
  '/environments/library/subagents': typeof AuthenticatedEnvironmentsLibrarySubagentsRoute
  '/settings/providers/$provider': typeof AuthenticatedSettingsProvidersProviderRoute
  '/environments/library/': typeof AuthenticatedEnvironmentsLibraryIndexRoute
  '/settings/providers/': typeof AuthenticatedSettingsProvidersIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/gallery': typeof AuthenticatedGalleryRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/': typeof AuthenticatedIndexRoute
  '/environments/agents': typeof AuthenticatedEnvironmentsAgentsRoute
  '/environments/health': typeof AuthenticatedEnvironmentsHealthRoute
  '/environments/runtimes': typeof AuthenticatedEnvironmentsRuntimesRoute
  '/library/$resourceKey': typeof AuthenticatedLibraryResourceKeyRoute
  '/library/backups': typeof AuthenticatedLibraryBackupsRoute
  '/library/instructions': typeof AuthenticatedLibraryInstructionsRoute
  '/library/settings': typeof AuthenticatedLibrarySettingsRoute
  '/library/skills': typeof AuthenticatedLibrarySkillsRoute
  '/library/subagents': typeof AuthenticatedLibrarySubagentsRoute
  '/settings/agents': typeof AuthenticatedSettingsAgentsRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/connectors': typeof AuthenticatedSettingsConnectorsRoute
  '/settings/context': typeof AuthenticatedSettingsContextRoute
  '/settings/external-api': typeof AuthenticatedSettingsExternalApiRoute
  '/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/settings/git': typeof AuthenticatedSettingsGitRoute
  '/settings/logs': typeof AuthenticatedSettingsLogsRoute
  '/settings/mcp': typeof AuthenticatedSettingsMcpRoute
  '/settings/metrics': typeof AuthenticatedSettingsMetricsRoute
  '/settings/prompts': typeof AuthenticatedSettingsPromptsRoute
  '/settings/skills': typeof AuthenticatedSettingsSkillsRoute
  '/settings/tools': typeof AuthenticatedSettingsToolsRoute
  '/environments': typeof AuthenticatedEnvironmentsIndexRoute
  '/library': typeof AuthenticatedLibraryIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/environments/library/$resourceKey': typeof AuthenticatedEnvironmentsLibraryResourceKeyRoute
  '/environments/library/backups': typeof AuthenticatedEnvironmentsLibraryBackupsRoute
  '/environments/library/instructions': typeof AuthenticatedEnvironmentsLibraryInstructionsRoute
  '/environments/library/settings': typeof AuthenticatedEnvironmentsLibrarySettingsRoute
  '/environments/library/skills': typeof AuthenticatedEnvironmentsLibrarySkillsRoute
  '/environments/library/subagents': typeof AuthenticatedEnvironmentsLibrarySubagentsRoute
  '/settings/providers/$provider': typeof AuthenticatedSettingsProvidersProviderRoute
  '/environments/library': typeof AuthenticatedEnvironmentsLibraryIndexRoute
  '/settings/providers': typeof AuthenticatedSettingsProvidersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/environments': typeof AuthenticatedEnvironmentsRouteWithChildren
  '/_authenticated/gallery': typeof AuthenticatedGalleryRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/studio': typeof AuthenticatedStudioRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/environments/agents': typeof AuthenticatedEnvironmentsAgentsRoute
  '/_authenticated/environments/health': typeof AuthenticatedEnvironmentsHealthRoute
  '/_authenticated/environments/library': typeof AuthenticatedEnvironmentsLibraryRouteWithChildren
  '/_authenticated/environments/runtimes': typeof AuthenticatedEnvironmentsRuntimesRoute
  '/_authenticated/library/$resourceKey': typeof AuthenticatedLibraryResourceKeyRoute
  '/_authenticated/library/backups': typeof AuthenticatedLibraryBackupsRoute
  '/_authenticated/library/instructions': typeof AuthenticatedLibraryInstructionsRoute
  '/_authenticated/library/settings': typeof AuthenticatedLibrarySettingsRoute
  '/_authenticated/library/skills': typeof AuthenticatedLibrarySkillsRoute
  '/_authenticated/library/subagents': typeof AuthenticatedLibrarySubagentsRoute
  '/_authenticated/settings/agents': typeof AuthenticatedSettingsAgentsRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/connectors': typeof AuthenticatedSettingsConnectorsRoute
  '/_authenticated/settings/context': typeof AuthenticatedSettingsContextRoute
  '/_authenticated/settings/external-api': typeof AuthenticatedSettingsExternalApiRoute
  '/_authenticated/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/_authenticated/settings/git': typeof AuthenticatedSettingsGitRoute
  '/_authenticated/settings/logs': typeof AuthenticatedSettingsLogsRoute
  '/_authenticated/settings/mcp': typeof AuthenticatedSettingsMcpRoute
  '/_authenticated/settings/metrics': typeof AuthenticatedSettingsMetricsRoute
  '/_authenticated/settings/prompts': typeof AuthenticatedSettingsPromptsRoute
  '/_authenticated/settings/providers': typeof AuthenticatedSettingsProvidersRouteWithChildren
  '/_authenticated/settings/skills': typeof AuthenticatedSettingsSkillsRoute
  '/_authenticated/settings/tools': typeof AuthenticatedSettingsToolsRoute
  '/_authenticated/environments/': typeof AuthenticatedEnvironmentsIndexRoute
  '/_authenticated/library/': typeof AuthenticatedLibraryIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/environments/library/$resourceKey': typeof AuthenticatedEnvironmentsLibraryResourceKeyRoute
  '/_authenticated/environments/library/backups': typeof AuthenticatedEnvironmentsLibraryBackupsRoute
  '/_authenticated/environments/library/instructions': typeof AuthenticatedEnvironmentsLibraryInstructionsRoute
  '/_authenticated/environments/library/settings': typeof AuthenticatedEnvironmentsLibrarySettingsRoute
  '/_authenticated/environments/library/skills': typeof AuthenticatedEnvironmentsLibrarySkillsRoute
  '/_authenticated/environments/library/subagents': typeof AuthenticatedEnvironmentsLibrarySubagentsRoute
  '/_authenticated/settings/providers/$provider': typeof AuthenticatedSettingsProvidersProviderRoute
  '/_authenticated/environments/library/': typeof AuthenticatedEnvironmentsLibraryIndexRoute
  '/_authenticated/settings/providers/': typeof AuthenticatedSettingsProvidersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/environments'
    | '/gallery'
    | '/settings'
    | '/studio'
    | '/environments/agents'
    | '/environments/health'
    | '/environments/library'
    | '/environments/runtimes'
    | '/library/$resourceKey'
    | '/library/backups'
    | '/library/instructions'
    | '/library/settings'
    | '/library/skills'
    | '/library/subagents'
    | '/settings/agents'
    | '/settings/appearance'
    | '/settings/connectors'
    | '/settings/context'
    | '/settings/external-api'
    | '/settings/general'
    | '/settings/git'
    | '/settings/logs'
    | '/settings/mcp'
    | '/settings/metrics'
    | '/settings/prompts'
    | '/settings/providers'
    | '/settings/skills'
    | '/settings/tools'
    | '/environments/'
    | '/library/'
    | '/settings/'
    | '/environments/library/$resourceKey'
    | '/environments/library/backups'
    | '/environments/library/instructions'
    | '/environments/library/settings'
    | '/environments/library/skills'
    | '/environments/library/subagents'
    | '/settings/providers/$provider'
    | '/environments/library/'
    | '/settings/providers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/gallery'
    | '/studio'
    | '/'
    | '/environments/agents'
    | '/environments/health'
    | '/environments/runtimes'
    | '/library/$resourceKey'
    | '/library/backups'
    | '/library/instructions'
    | '/library/settings'
    | '/library/skills'
    | '/library/subagents'
    | '/settings/agents'
    | '/settings/appearance'
    | '/settings/connectors'
    | '/settings/context'
    | '/settings/external-api'
    | '/settings/general'
    | '/settings/git'
    | '/settings/logs'
    | '/settings/mcp'
    | '/settings/metrics'
    | '/settings/prompts'
    | '/settings/skills'
    | '/settings/tools'
    | '/environments'
    | '/library'
    | '/settings'
    | '/environments/library/$resourceKey'
    | '/environments/library/backups'
    | '/environments/library/instructions'
    | '/environments/library/settings'
    | '/environments/library/skills'
    | '/environments/library/subagents'
    | '/settings/providers/$provider'
    | '/environments/library'
    | '/settings/providers'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/environments'
    | '/_authenticated/gallery'
    | '/_authenticated/settings'
    | '/_authenticated/studio'
    | '/_authenticated/'
    | '/_authenticated/environments/agents'
    | '/_authenticated/environments/health'
    | '/_authenticated/environments/library'
    | '/_authenticated/environments/runtimes'
    | '/_authenticated/library/$resourceKey'
    | '/_authenticated/library/backups'
    | '/_authenticated/library/instructions'
    | '/_authenticated/library/settings'
    | '/_authenticated/library/skills'
    | '/_authenticated/library/subagents'
    | '/_authenticated/settings/agents'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/connectors'
    | '/_authenticated/settings/context'
    | '/_authenticated/settings/external-api'
    | '/_authenticated/settings/general'
    | '/_authenticated/settings/git'
    | '/_authenticated/settings/logs'
    | '/_authenticated/settings/mcp'
    | '/_authenticated/settings/metrics'
    | '/_authenticated/settings/prompts'
    | '/_authenticated/settings/providers'
    | '/_authenticated/settings/skills'
    | '/_authenticated/settings/tools'
    | '/_authenticated/environments/'
    | '/_authenticated/library/'
    | '/_authenticated/settings/'
    | '/_authenticated/environments/library/$resourceKey'
    | '/_authenticated/environments/library/backups'
    | '/_authenticated/environments/library/instructions'
    | '/_authenticated/environments/library/settings'
    | '/_authenticated/environments/library/skills'
    | '/_authenticated/environments/library/subagents'
    | '/_authenticated/settings/providers/$provider'
    | '/_authenticated/environments/library/'
    | '/_authenticated/settings/providers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/studio': {
      id: '/_authenticated/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AuthenticatedStudioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gallery': {
      id: '/_authenticated/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof AuthenticatedGalleryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/environments': {
      id: '/_authenticated/environments'
      path: '/environments'
      fullPath: '/environments'
      preLoaderRoute: typeof AuthenticatedEnvironmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/library/': {
      id: '/_authenticated/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof AuthenticatedLibraryIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/environments/': {
      id: '/_authenticated/environments/'
      path: '/'
      fullPath: '/environments/'
      preLoaderRoute: typeof AuthenticatedEnvironmentsIndexRouteImport
      parentRoute: typeof AuthenticatedEnvironmentsRoute
    }
    '/_authenticated/settings/tools': {
      id: '/_authenticated/settings/tools'
      path: '/tools'
      fullPath: '/settings/tools'
      preLoaderRoute: typeof AuthenticatedSettingsToolsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/skills': {
      id: '/_authenticated/settings/skills'
      path: '/skills'
      fullPath: '/settings/skills'
      preLoaderRoute: typeof AuthenticatedSettingsSkillsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/providers': {
      id: '/_authenticated/settings/providers'
      path: '/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof AuthenticatedSettingsProvidersRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/prompts': {
      id: '/_authenticated/settings/prompts'
      path: '/prompts'
      fullPath: '/settings/prompts'
      preLoaderRoute: typeof AuthenticatedSettingsPromptsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/metrics': {
      id: '/_authenticated/settings/metrics'
      path: '/metrics'
      fullPath: '/settings/metrics'
      preLoaderRoute: typeof AuthenticatedSettingsMetricsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/mcp': {
      id: '/_authenticated/settings/mcp'
      path: '/mcp'
      fullPath: '/settings/mcp'
      preLoaderRoute: typeof AuthenticatedSettingsMcpRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/logs': {
      id: '/_authenticated/settings/logs'
      path: '/logs'
      fullPath: '/settings/logs'
      preLoaderRoute: typeof AuthenticatedSettingsLogsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/git': {
      id: '/_authenticated/settings/git'
      path: '/git'
      fullPath: '/settings/git'
      preLoaderRoute: typeof AuthenticatedSettingsGitRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/general': {
      id: '/_authenticated/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof AuthenticatedSettingsGeneralRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/external-api': {
      id: '/_authenticated/settings/external-api'
      path: '/external-api'
      fullPath: '/settings/external-api'
      preLoaderRoute: typeof AuthenticatedSettingsExternalApiRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/context': {
      id: '/_authenticated/settings/context'
      path: '/context'
      fullPath: '/settings/context'
      preLoaderRoute: typeof AuthenticatedSettingsContextRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/connectors': {
      id: '/_authenticated/settings/connectors'
      path: '/connectors'
      fullPath: '/settings/connectors'
      preLoaderRoute: typeof AuthenticatedSettingsConnectorsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/agents': {
      id: '/_authenticated/settings/agents'
      path: '/agents'
      fullPath: '/settings/agents'
      preLoaderRoute: typeof AuthenticatedSettingsAgentsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/library/subagents': {
      id: '/_authenticated/library/subagents'
      path: '/library/subagents'
      fullPath: '/library/subagents'
      preLoaderRoute: typeof AuthenticatedLibrarySubagentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/library/skills': {
      id: '/_authenticated/library/skills'
      path: '/library/skills'
      fullPath: '/library/skills'
      preLoaderRoute: typeof AuthenticatedLibrarySkillsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/library/settings': {
      id: '/_authenticated/library/settings'
      path: '/library/settings'
      fullPath: '/library/settings'
      preLoaderRoute: typeof AuthenticatedLibrarySettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/library/instructions': {
      id: '/_authenticated/library/instructions'
      path: '/library/instructions'
      fullPath: '/library/instructions'
      preLoaderRoute: typeof AuthenticatedLibraryInstructionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/library/backups': {
      id: '/_authenticated/library/backups'
      path: '/library/backups'
      fullPath: '/library/backups'
      preLoaderRoute: typeof AuthenticatedLibraryBackupsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/library/$resourceKey': {
      id: '/_authenticated/library/$resourceKey'
      path: '/library/$resourceKey'
      fullPath: '/library/$resourceKey'
      preLoaderRoute: typeof AuthenticatedLibraryResourceKeyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/environments/runtimes': {
      id: '/_authenticated/environments/runtimes'
      path: '/runtimes'
      fullPath: '/environments/runtimes'
      preLoaderRoute: typeof AuthenticatedEnvironmentsRuntimesRouteImport
      parentRoute: typeof AuthenticatedEnvironmentsRoute
    }
    '/_authenticated/environments/library': {
      id: '/_authenticated/environments/library'
      path: '/library'
      fullPath: '/environments/library'
      preLoaderRoute: typeof AuthenticatedEnvironmentsLibraryRouteImport
      parentRoute: typeof AuthenticatedEnvironmentsRoute
    }
    '/_authenticated/environments/health': {
      id: '/_authenticated/environments/health'
      path: '/health'
      fullPath: '/environments/health'
      preLoaderRoute: typeof AuthenticatedEnvironmentsHealthRouteImport
      parentRoute: typeof AuthenticatedEnvironmentsRoute
    }
    '/_authenticated/environments/agents': {
      id: '/_authenticated/environments/agents'
      path: '/agents'
      fullPath: '/environments/agents'
      preLoaderRoute: typeof AuthenticatedEnvironmentsAgentsRouteImport
      parentRoute: typeof AuthenticatedEnvironmentsRoute
    }
    '/_authenticated/settings/providers/': {
      id: '/_authenticated/settings/providers/'
      path: '/'
      fullPath: '/settings/providers/'
      preLoaderRoute: typeof AuthenticatedSettingsProvidersIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsProvidersRoute
    }
    '/_authenticated/environments/library/': {
      id: '/_authenticated/environments/library/'
      path: '/'
      fullPath: '/environments/library/'
      preLoaderRoute: typeof AuthenticatedEnvironmentsLibraryIndexRouteImport
      parentRoute: typeof AuthenticatedEnvironmentsLibraryRoute
    }
    '/_authenticated/settings/providers/$provider': {
      id: '/_authenticated/settings/providers/$provider'
      path: '/$provider'
      fullPath: '/settings/providers/$provider'
      preLoaderRoute: typeof AuthenticatedSettingsProvidersProviderRouteImport
      parentRoute: typeof AuthenticatedSettingsProvidersRoute
    }
    '/_authenticated/environments/library/subagents': {
      id: '/_authenticated/environments/library/subagents'
      path: '/subagents'
      fullPath: '/environments/library/subagents'
      preLoaderRoute: typeof AuthenticatedEnvironmentsLibrarySubagentsRouteImport
      parentRoute: typeof AuthenticatedEnvironmentsLibraryRoute
    }
    '/_authenticated/environments/library/skills': {
      id: '/_authenticated/environments/library/skills'
      path: '/skills'
      fullPath: '/environments/library/skills'
      preLoaderRoute: typeof AuthenticatedEnvironmentsLibrarySkillsRouteImport
      parentRoute: typeof AuthenticatedEnvironmentsLibraryRoute
    }
    '/_authenticated/environments/library/settings': {
      id: '/_authenticated/environments/library/settings'
      path: '/settings'
      fullPath: '/environments/library/settings'
      preLoaderRoute: typeof AuthenticatedEnvironmentsLibrarySettingsRouteImport
      parentRoute: typeof AuthenticatedEnvironmentsLibraryRoute
    }
    '/_authenticated/environments/library/instructions': {
      id: '/_authenticated/environments/library/instructions'
      path: '/instructions'
      fullPath: '/environments/library/instructions'
      preLoaderRoute: typeof AuthenticatedEnvironmentsLibraryInstructionsRouteImport
      parentRoute: typeof AuthenticatedEnvironmentsLibraryRoute
    }
    '/_authenticated/environments/library/backups': {
      id: '/_authenticated/environments/library/backups'
      path: '/backups'
      fullPath: '/environments/library/backups'
      preLoaderRoute: typeof AuthenticatedEnvironmentsLibraryBackupsRouteImport
      parentRoute: typeof AuthenticatedEnvironmentsLibraryRoute
    }
    '/_authenticated/environments/library/$resourceKey': {
      id: '/_authenticated/environments/library/$resourceKey'
      path: '/$resourceKey'
      fullPath: '/environments/library/$resourceKey'
      preLoaderRoute: typeof AuthenticatedEnvironmentsLibraryResourceKeyRouteImport
      parentRoute: typeof AuthenticatedEnvironmentsLibraryRoute
    }
  }
}

interface AuthenticatedEnvironmentsLibraryRouteChildren {
  AuthenticatedEnvironmentsLibraryResourceKeyRoute: typeof AuthenticatedEnvironmentsLibraryResourceKeyRoute
  AuthenticatedEnvironmentsLibraryBackupsRoute: typeof AuthenticatedEnvironmentsLibraryBackupsRoute
  AuthenticatedEnvironmentsLibraryInstructionsRoute: typeof AuthenticatedEnvironmentsLibraryInstructionsRoute
  AuthenticatedEnvironmentsLibrarySettingsRoute: typeof AuthenticatedEnvironmentsLibrarySettingsRoute
  AuthenticatedEnvironmentsLibrarySkillsRoute: typeof AuthenticatedEnvironmentsLibrarySkillsRoute
  AuthenticatedEnvironmentsLibrarySubagentsRoute: typeof AuthenticatedEnvironmentsLibrarySubagentsRoute
  AuthenticatedEnvironmentsLibraryIndexRoute: typeof AuthenticatedEnvironmentsLibraryIndexRoute
}

const AuthenticatedEnvironmentsLibraryRouteChildren: AuthenticatedEnvironmentsLibraryRouteChildren =
  {
    AuthenticatedEnvironmentsLibraryResourceKeyRoute:
      AuthenticatedEnvironmentsLibraryResourceKeyRoute,
    AuthenticatedEnvironmentsLibraryBackupsRoute:
      AuthenticatedEnvironmentsLibraryBackupsRoute,
    AuthenticatedEnvironmentsLibraryInstructionsRoute:
      AuthenticatedEnvironmentsLibraryInstructionsRoute,
    AuthenticatedEnvironmentsLibrarySettingsRoute:
      AuthenticatedEnvironmentsLibrarySettingsRoute,
    AuthenticatedEnvironmentsLibrarySkillsRoute:
      AuthenticatedEnvironmentsLibrarySkillsRoute,
    AuthenticatedEnvironmentsLibrarySubagentsRoute:
      AuthenticatedEnvironmentsLibrarySubagentsRoute,
    AuthenticatedEnvironmentsLibraryIndexRoute:
      AuthenticatedEnvironmentsLibraryIndexRoute,
  }

const AuthenticatedEnvironmentsLibraryRouteWithChildren =
  AuthenticatedEnvironmentsLibraryRoute._addFileChildren(
    AuthenticatedEnvironmentsLibraryRouteChildren,
  )

interface AuthenticatedEnvironmentsRouteChildren {
  AuthenticatedEnvironmentsAgentsRoute: typeof AuthenticatedEnvironmentsAgentsRoute
  AuthenticatedEnvironmentsHealthRoute: typeof AuthenticatedEnvironmentsHealthRoute
  AuthenticatedEnvironmentsLibraryRoute: typeof AuthenticatedEnvironmentsLibraryRouteWithChildren
  AuthenticatedEnvironmentsRuntimesRoute: typeof AuthenticatedEnvironmentsRuntimesRoute
  AuthenticatedEnvironmentsIndexRoute: typeof AuthenticatedEnvironmentsIndexRoute
}

const AuthenticatedEnvironmentsRouteChildren: AuthenticatedEnvironmentsRouteChildren =
  {
    AuthenticatedEnvironmentsAgentsRoute: AuthenticatedEnvironmentsAgentsRoute,
    AuthenticatedEnvironmentsHealthRoute: AuthenticatedEnvironmentsHealthRoute,
    AuthenticatedEnvironmentsLibraryRoute:
      AuthenticatedEnvironmentsLibraryRouteWithChildren,
    AuthenticatedEnvironmentsRuntimesRoute:
      AuthenticatedEnvironmentsRuntimesRoute,
    AuthenticatedEnvironmentsIndexRoute: AuthenticatedEnvironmentsIndexRoute,
  }

const AuthenticatedEnvironmentsRouteWithChildren =
  AuthenticatedEnvironmentsRoute._addFileChildren(
    AuthenticatedEnvironmentsRouteChildren,
  )

interface AuthenticatedSettingsProvidersRouteChildren {
  AuthenticatedSettingsProvidersProviderRoute: typeof AuthenticatedSettingsProvidersProviderRoute
  AuthenticatedSettingsProvidersIndexRoute: typeof AuthenticatedSettingsProvidersIndexRoute
}

const AuthenticatedSettingsProvidersRouteChildren: AuthenticatedSettingsProvidersRouteChildren =
  {
    AuthenticatedSettingsProvidersProviderRoute:
      AuthenticatedSettingsProvidersProviderRoute,
    AuthenticatedSettingsProvidersIndexRoute:
      AuthenticatedSettingsProvidersIndexRoute,
  }

const AuthenticatedSettingsProvidersRouteWithChildren =
  AuthenticatedSettingsProvidersRoute._addFileChildren(
    AuthenticatedSettingsProvidersRouteChildren,
  )

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsAgentsRoute: typeof AuthenticatedSettingsAgentsRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsConnectorsRoute: typeof AuthenticatedSettingsConnectorsRoute
  AuthenticatedSettingsContextRoute: typeof AuthenticatedSettingsContextRoute
  AuthenticatedSettingsExternalApiRoute: typeof AuthenticatedSettingsExternalApiRoute
  AuthenticatedSettingsGeneralRoute: typeof AuthenticatedSettingsGeneralRoute
  AuthenticatedSettingsGitRoute: typeof AuthenticatedSettingsGitRoute
  AuthenticatedSettingsLogsRoute: typeof AuthenticatedSettingsLogsRoute
  AuthenticatedSettingsMcpRoute: typeof AuthenticatedSettingsMcpRoute
  AuthenticatedSettingsMetricsRoute: typeof AuthenticatedSettingsMetricsRoute
  AuthenticatedSettingsPromptsRoute: typeof AuthenticatedSettingsPromptsRoute
  AuthenticatedSettingsProvidersRoute: typeof AuthenticatedSettingsProvidersRouteWithChildren
  AuthenticatedSettingsSkillsRoute: typeof AuthenticatedSettingsSkillsRoute
  AuthenticatedSettingsToolsRoute: typeof AuthenticatedSettingsToolsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsAgentsRoute: AuthenticatedSettingsAgentsRoute,
  AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
  AuthenticatedSettingsConnectorsRoute: AuthenticatedSettingsConnectorsRoute,
  AuthenticatedSettingsContextRoute: AuthenticatedSettingsContextRoute,
  AuthenticatedSettingsExternalApiRoute: AuthenticatedSettingsExternalApiRoute,
  AuthenticatedSettingsGeneralRoute: AuthenticatedSettingsGeneralRoute,
  AuthenticatedSettingsGitRoute: AuthenticatedSettingsGitRoute,
  AuthenticatedSettingsLogsRoute: AuthenticatedSettingsLogsRoute,
  AuthenticatedSettingsMcpRoute: AuthenticatedSettingsMcpRoute,
  AuthenticatedSettingsMetricsRoute: AuthenticatedSettingsMetricsRoute,
  AuthenticatedSettingsPromptsRoute: AuthenticatedSettingsPromptsRoute,
  AuthenticatedSettingsProvidersRoute:
    AuthenticatedSettingsProvidersRouteWithChildren,
  AuthenticatedSettingsSkillsRoute: AuthenticatedSettingsSkillsRoute,
  AuthenticatedSettingsToolsRoute: AuthenticatedSettingsToolsRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedEnvironmentsRoute: typeof AuthenticatedEnvironmentsRouteWithChildren
  AuthenticatedGalleryRoute: typeof AuthenticatedGalleryRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedStudioRoute: typeof AuthenticatedStudioRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedLibraryResourceKeyRoute: typeof AuthenticatedLibraryResourceKeyRoute
  AuthenticatedLibraryBackupsRoute: typeof AuthenticatedLibraryBackupsRoute
  AuthenticatedLibraryInstructionsRoute: typeof AuthenticatedLibraryInstructionsRoute
  AuthenticatedLibrarySettingsRoute: typeof AuthenticatedLibrarySettingsRoute
  AuthenticatedLibrarySkillsRoute: typeof AuthenticatedLibrarySkillsRoute
  AuthenticatedLibrarySubagentsRoute: typeof AuthenticatedLibrarySubagentsRoute
  AuthenticatedLibraryIndexRoute: typeof AuthenticatedLibraryIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedEnvironmentsRoute: AuthenticatedEnvironmentsRouteWithChildren,
  AuthenticatedGalleryRoute: AuthenticatedGalleryRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedStudioRoute: AuthenticatedStudioRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedLibraryResourceKeyRoute: AuthenticatedLibraryResourceKeyRoute,
  AuthenticatedLibraryBackupsRoute: AuthenticatedLibraryBackupsRoute,
  AuthenticatedLibraryInstructionsRoute: AuthenticatedLibraryInstructionsRoute,
  AuthenticatedLibrarySettingsRoute: AuthenticatedLibrarySettingsRoute,
  AuthenticatedLibrarySkillsRoute: AuthenticatedLibrarySkillsRoute,
  AuthenticatedLibrarySubagentsRoute: AuthenticatedLibrarySubagentsRoute,
  AuthenticatedLibraryIndexRoute: AuthenticatedLibraryIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
